# Generated by Django 2.1.4 on 2018-12-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
                ('lat', models.CharField(max_length=30)),
                ('lon', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=7)),
                ('dst', models.CharField(max_length=1)),
                ('alt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('capital_name', models.CharField(max_length=25)),
                ('capital_lat', models.CharField(max_length=20)),
                ('capital_lon', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=6)),
                ('continent_name', models.CharField(max_length=16)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('orig', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('gps', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ManyToManyField(to='travels.Country')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Travel'),
        ),
        migrations.AddField(
            model_name='journey',
            name='transport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.Transport'),
        ),
        migrations.AddField(
            model_name='journey',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Travel'),
        ),
    ]
