# Generated by Django 2.1.4 on 2018-12-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fldate', models.DateTimeField()),
                ('flfrom', models.CharField(max_length=4)),
                ('flto', models.CharField(max_length=4)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(blank=True, max_length=40, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('seat', models.CharField(blank=True, max_length=6, null=True)),
                ('seat_type', models.CharField(blank=True, max_length=2, null=True)),
                ('flclass', models.CharField(blank=True, max_length=2, null=True)),
                ('reason', models.CharField(blank=True, max_length=2, null=True)),
                ('plane', models.CharField(blank=True, max_length=40, null=True)),
                ('registration', models.CharField(blank=True, max_length=10, null=True)),
                ('trip', models.CharField(blank=True, max_length=5, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('from_oid', models.CharField(blank=True, max_length=10, null=True)),
                ('to_oid', models.CharField(blank=True, max_length=10, null=True)),
                ('airline_oid', models.CharField(blank=True, max_length=10, null=True)),
                ('flfrom2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flfrom2', to='travels.Airport')),
                ('flto2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flto2', to='travels.Airport')),
            ],
        ),
    ]
