# Generated by Django 2.1.4 on 2018-12-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20181230_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.Travel'),
        ),
    ]
