# Generated by Django 2.1.4 on 2019-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_flight_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='journey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
