# Generated by Django 2.1.4 on 2019-01-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20190103_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['fldate']},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flclass',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='from_oid',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_oid',
        ),
    ]
