# Generated by Django 2.1.4 on 2019-01-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_auto_20190105_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='fldate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flfrom',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flfrom2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flto',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flto2',
        ),
        migrations.AddField(
            model_name='flight',
            name='dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest', to='travels.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orig', to='travels.Airport'),
        ),
    ]
