# Generated by Django 2.1.4 on 2019-01-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20190105_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='trip',
        ),
    ]
