# Generated by Django 2.1.4 on 2019-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_remove_flight_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
