# Generated by Django 2.1.4 on 2019-01-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_auto_20190109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.Country'),
        ),
    ]
