# Generated by Django 2.1.5 on 2019-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_auto_20190109_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('iata', models.CharField(blank=True, max_length=3, null=True)),
                ('icao', models.CharField(blank=True, max_length=5, null=True)),
                ('callsign', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
