# Generated by Django 2.1.5 on 2019-01-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0014_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.Airline'),
        ),
    ]
