# Generated by Django 2.1.5 on 2019-01-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_flight_airline2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline_oid',
        ),
    ]
