# Generated by Django 2.1.5 on 2019-01-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_auto_20190115_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline2',
            new_name='airline',
        ),
    ]
