# Generated by Django 2.1.5 on 2019-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0017_auto_20190115_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
