# Generated by Django 2.1.5 on 2019-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0018_auto_20190115_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='currency2',
            field=models.CharField(blank=True, choices=[('PLN', 'PLN Polish Złoty'), ('USD', 'USD Dollar'), ('EUR', 'EUR Euro'), ('GBP', 'GBP British Pound')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='distance2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
