# Generated by Django 2.1.5 on 2019-01-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0020_remove_flight_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='currency2',
            new_name='currency',
        ),
    ]
