# Generated by Django 2.1.5 on 2019-01-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_auto_20190115_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
