# Generated by Django 2.1.5 on 2019-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0022_auto_20190115_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='distance',
        ),
    ]
