# Generated by Django 2.1.5 on 2019-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0023_remove_flight_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='distance2',
            new_name='distance',
        ),
    ]
