# Generated by Django 2.1.5 on 2019-01-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0024_auto_20190115_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
