# Generated by Django 2.1.5 on 2019-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0025_flight_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
