# Generated by Django 2.1.5 on 2019-01-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0026_flight_date2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date2']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
    ]
