# Generated by Django 2.1.5 on 2019-01-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0028_auto_20190116_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='key_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airline', to='travels.Airline'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='travels.Country'),
        ),
    ]
