# Generated by Django 2.1.5 on 2019-01-20 12:05

from django.db import migrations, models
import travels.models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0029_auto_20190119_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='boarding_pass',
            field=models.ImageField(blank=True, null=True, upload_to=travels.models.flight_upload_location),
        ),
        migrations.AlterField(
            model_name='travel',
            name='key_photo',
            field=models.ImageField(blank=True, null=True, upload_to=travels.models.travel_upload_location),
        ),
    ]
