# Generated by Django 2.2.5 on 2019-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0032_auto_20190917_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='place / hotel'),
        ),
    ]
